import {
  Combine,
  Minimize2,
  Scissors,
  RotateCw,
  Trash2,
  FileOutput,
  ArrowDownUp,
  Crop,
  FilePlus2,
  Hash,
  Type,
  TextCursorInput,
  Highlighter,
  Underline,
  Strikethrough,
  ImagePlus,
  Stamp,
  Eraser,
  Shapes,
  Pencil,
  StickyNote,
  Link2,
  FormInput,
  ListChecks,
  FileX2,
  Layers,
  PenTool,
  Calendar,
  CheckSquare,
  CircleDot,
  ChevronDownSquare,
  Lock,
  Unlock,
  SquareM,
  FileLock2,
  FileKey2,
  ShieldAlert,
  Tags,
  ScanText,
  FileSearch,
  FileType2,
  Images,
  FileImage,
  ImageDown,
  FileText,
  FileCode2,
  FileSpreadsheet,
  Presentation,
  Globe,
  Eye,
  GitCompareArrows,
  Info,
  Ruler,
  LayoutGrid,
  CopyPlus,
  Replace,
  FileDigit,
} from "lucide-react";
import type { Tool, ToolFaq } from "@/types";

const PDF_ACCEPT = ["application/pdf"];
const IMAGE_ACCEPT = ["image/jpeg", "image/png", "image/webp"];

const privacyFaq: ToolFaq = {
  question: "Are my files uploaded to a server?",
  answer:
    "Never. Every operation runs entirely inside your browser using WebAssembly and JavaScript. Your document never leaves your device, so it is 100% private by design.",
};

const freeFaq: ToolFaq = {
  question: "Is this tool free to use?",
  answer:
    "Yes. All core tools are free with no watermarks, no sign-up and no daily limits because the processing happens on your own machine.",
};

const qualityFaq: ToolFaq = {
  question: "Will the quality of my PDF change?",
  answer:
    "We preserve your original content and structure wherever possible. Operations are lossless unless you explicitly choose a compression or rasterization option.",
};

/** Shared FAQ tail appended to every tool. */
const commonFaqs = [privacyFaq, freeFaq, qualityFaq];

function steps(a: string, b: string, c: string): Tool["steps"] {
  return [
    { title: "Upload", description: a },
    { title: "Configure", description: b },
    { title: "Download", description: c },
  ];
}

export const TOOLS: Tool[] = [
  /* ------------------------------------------------------------------ */
  /* ORGANIZE                                                            */
  /* ------------------------------------------------------------------ */
  {
    slug: "merge",
    title: "Merge PDF",
    short: "Combine PDFs into one",
    description:
      "Combine multiple PDF files into a single, perfectly ordered document. Drag to reorder before you merge.",
    category: "organize",
    icon: Combine,
    handler: "processor",
    processorId: "merge",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF files",
    multiple: true,
    minFiles: 2,
    maxFiles: 40,
    gradient: "from-indigo-500 to-violet-500",
    popular: true,
    outputSuffix: "merged",
    keywords: ["combine", "join", "concatenate", "bind"],
    steps: steps(
      "Select two or more PDF files from your device.",
      "Drag the files into the exact order you want.",
      "Download one combined PDF, assembled in your browser."
    ),
    benefits: [
      "Merge up to 40 documents at once",
      "Reorder files with drag & drop",
      "Bookmarks and page sizes preserved",
    ],
    faqs: [
      {
        question: "Can I change the order of the files?",
        answer:
          "Yes. After uploading, drag any file up or down in the list to set the exact page order before merging.",
      },
      ...commonFaqs,
    ],
  },
  {
    slug: "compress",
    title: "Compress PDF",
    short: "Shrink file size",
    description:
      "Dramatically reduce PDF file size while keeping the best possible visual quality. Choose your compression level.",
    category: "organize",
    icon: Minimize2,
    handler: "processor",
    processorId: "compress",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-emerald-500 to-teal-500",
    popular: true,
    outputSuffix: "compressed",
    keywords: ["reduce", "smaller", "optimize", "shrink", "size"],
    options: [
      {
        id: "level",
        label: "Compression level",
        type: "radio",
        default: "balanced",
        options: [
          { label: "Light", value: "light", description: "Best quality, modest size reduction" },
          { label: "Balanced", value: "balanced", description: "Great quality with strong savings" },
          { label: "Strong", value: "strong", description: "Smallest size, images downscaled" },
        ],
      },
    ],
    steps: steps(
      "Choose the PDF you want to make smaller.",
      "Pick a compression level from light to strong.",
      "Download your optimized, lighter PDF."
    ),
    benefits: [
      "Reduce size by up to 80%",
      "Smart image downsampling",
      "Perfect for email and uploads",
    ],
    faqs: [
      {
        question: "How much smaller will my file get?",
        answer:
          "It depends on the content. Image-heavy PDFs can shrink by 50–80%, while text-only files see smaller gains. We show you the exact savings after processing.",
      },
      ...commonFaqs,
    ],
  },
  {
    slug: "split",
    title: "Split PDF",
    short: "Separate into files",
    description:
      "Split one PDF into multiple files by page ranges, or extract every page into its own document.",
    category: "organize",
    icon: Scissors,
    handler: "processor",
    processorId: "split",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-orange-500 to-amber-500",
    popular: true,
    outputSuffix: "split",
    keywords: ["divide", "separate", "cut", "pages"],
    options: [
      {
        id: "mode",
        label: "Split mode",
        type: "radio",
        default: "ranges",
        options: [
          { label: "By ranges", value: "ranges", description: "Extract specific page ranges" },
          { label: "Every page", value: "each", description: "One file per page" },
          { label: "Fixed size", value: "fixed", description: "Every N pages" },
        ],
      },
      {
        id: "ranges",
        label: "Page ranges",
        type: "text",
        default: "1-3, 4-6",
        placeholder: "e.g. 1-3, 5, 8-10",
        help: "Each range becomes its own PDF.",
        showWhen: { id: "mode", equals: "ranges" },
      },
      {
        id: "size",
        label: "Pages per file",
        type: "number",
        default: 2,
        min: 1,
        max: 500,
        showWhen: { id: "mode", equals: "fixed" },
      },
    ],
    steps: steps(
      "Upload the PDF you want to divide.",
      "Choose to split by ranges, per page, or in fixed chunks.",
      "Download a ZIP with each resulting PDF."
    ),
    benefits: ["Split by custom ranges", "Bundle results in a ZIP", "Extract single pages instantly"],
    faqs: commonFaqs,
  },
  {
    slug: "rotate",
    title: "Rotate PDF",
    short: "Fix page orientation",
    description:
      "Rotate all or selected pages by 90, 180 or 270 degrees to correct the orientation of your document.",
    category: "organize",
    icon: RotateCw,
    handler: "processor",
    processorId: "rotate",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-sky-500 to-indigo-500",
    outputSuffix: "rotated",
    keywords: ["turn", "orientation", "landscape", "portrait"],
    options: [
      {
        id: "angle",
        label: "Rotation",
        type: "radio",
        default: "90",
        options: [
          { label: "90° right", value: "90" },
          { label: "180°", value: "180" },
          { label: "270° left", value: "270" },
        ],
      },
      {
        id: "pages",
        label: "Apply to pages",
        type: "page-range",
        default: "",
        placeholder: "All pages (leave blank) or e.g. 1-3, 5",
      },
    ],
    steps: steps(
      "Upload the PDF that needs rotating.",
      "Pick an angle and optionally target specific pages.",
      "Download the correctly oriented PDF."
    ),
    benefits: ["Rotate specific pages", "Batch rotate all pages", "Lossless — no re-encoding"],
    faqs: commonFaqs,
  },
  {
    slug: "delete-pages",
    title: "Delete Pages",
    short: "Remove unwanted pages",
    description: "Remove one or more pages from your PDF and download a clean, trimmed document.",
    category: "organize",
    icon: Trash2,
    handler: "processor",
    processorId: "deletePages",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-rose-500 to-red-500",
    outputSuffix: "trimmed",
    keywords: ["remove", "erase", "drop pages"],
    options: [
      {
        id: "pages",
        label: "Pages to delete",
        type: "page-range",
        default: "1",
        placeholder: "e.g. 2, 5-7",
        help: "These pages will be removed from the document.",
      },
    ],
    steps: steps(
      "Upload your PDF.",
      "Enter the pages you want to remove.",
      "Download the document without those pages."
    ),
    benefits: ["Delete ranges at once", "Live page preview", "Original quality kept"],
    faqs: commonFaqs,
  },
  {
    slug: "extract-pages",
    title: "Extract Pages",
    short: "Pull out select pages",
    description: "Extract a selection of pages into a brand new PDF, leaving the original untouched.",
    category: "organize",
    icon: FileOutput,
    handler: "processor",
    processorId: "extractPages",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-violet-500 to-purple-500",
    outputSuffix: "extracted",
    keywords: ["pick", "select pages", "subset"],
    options: [
      {
        id: "pages",
        label: "Pages to extract",
        type: "page-range",
        default: "1-2",
        placeholder: "e.g. 1-2, 6",
      },
    ],
    steps: steps(
      "Upload the source PDF.",
      "Type the pages you want to keep.",
      "Download a new PDF with only those pages."
    ),
    benefits: ["Keep only what matters", "Maintain original order", "Instant, private extraction"],
    faqs: commonFaqs,
  },
  {
    slug: "organize",
    title: "Organize Pages",
    short: "Reorder & rearrange",
    description:
      "Visually rearrange, rotate and delete pages with an interactive thumbnail board, then rebuild your PDF.",
    category: "organize",
    icon: ArrowDownUp,
    handler: "processor",
    processorId: "organize",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-fuchsia-500 to-pink-500",
    popular: true,
    outputSuffix: "organized",
    keywords: ["rearrange", "reorder", "sort pages", "move"],
    steps: steps(
      "Upload your PDF to see every page as a thumbnail.",
      "Drag pages to reorder, rotate or delete them.",
      "Download the freshly organized document."
    ),
    benefits: ["Drag & drop reordering", "Rotate or remove per page", "Visual, tactile control"],
    faqs: commonFaqs,
  },
  {
    slug: "crop",
    title: "Crop PDF",
    short: "Trim page margins",
    description: "Trim white margins or crop every page to a consistent region for a cleaner layout.",
    category: "organize",
    icon: Crop,
    handler: "processor",
    processorId: "crop",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-teal-500 to-cyan-500",
    outputSuffix: "cropped",
    keywords: ["trim", "margins", "cut edges"],
    options: [
      {
        id: "margin",
        label: "Trim margin",
        type: "range",
        default: 24,
        min: 0,
        max: 120,
        step: 2,
        unit: "pt",
        help: "Equal amount trimmed from every edge.",
      },
    ],
    steps: steps(
      "Upload the PDF you want to crop.",
      "Set how much to trim from each edge.",
      "Download the tightened-up document."
    ),
    benefits: ["Uniform margin trimming", "Applies to every page", "Non-destructive crop box"],
    faqs: commonFaqs,
  },
  {
    slug: "add-blank-pages",
    title: "Add Blank Pages",
    short: "Insert empty pages",
    description: "Insert blank pages at any position — perfect for notes, printing or spacing.",
    category: "organize",
    icon: FilePlus2,
    handler: "processor",
    processorId: "addBlankPages",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-blue-500 to-indigo-500",
    outputSuffix: "with-pages",
    keywords: ["insert", "empty", "add pages"],
    options: [
      {
        id: "position",
        label: "Insert after page",
        type: "number",
        default: 1,
        min: 0,
        max: 999,
        help: "Use 0 to insert at the very beginning.",
      },
      { id: "count", label: "Number of pages", type: "number", default: 1, min: 1, max: 50 },
      {
        id: "size",
        label: "Page size",
        type: "select",
        default: "match",
        options: [
          { label: "Match document", value: "match" },
          { label: "A4", value: "a4" },
          { label: "US Letter", value: "letter" },
        ],
      },
    ],
    steps: steps(
      "Upload your PDF.",
      "Choose where and how many blank pages to add.",
      "Download the expanded document."
    ),
    benefits: ["Insert anywhere", "Match existing page size", "Great for print layouts"],
    faqs: commonFaqs,
  },
  {
    slug: "add-page-numbers",
    title: "Add Page Numbers",
    short: "Number every page",
    description: "Stamp elegant, customizable page numbers onto every page in seconds.",
    category: "organize",
    icon: Hash,
    handler: "processor",
    processorId: "addPageNumbers",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-amber-500 to-yellow-500",
    outputSuffix: "numbered",
    keywords: ["pagination", "footer", "numbers"],
    options: [
      {
        id: "position",
        label: "Position",
        type: "select",
        default: "bottom-center",
        options: [
          { label: "Bottom center", value: "bottom-center" },
          { label: "Bottom right", value: "bottom-right" },
          { label: "Bottom left", value: "bottom-left" },
          { label: "Top center", value: "top-center" },
          { label: "Top right", value: "top-right" },
          { label: "Top left", value: "top-left" },
        ],
      },
      {
        id: "format",
        label: "Format",
        type: "select",
        default: "n",
        options: [
          { label: "1, 2, 3", value: "n" },
          { label: "Page 1", value: "page-n" },
          { label: "1 of N", value: "n-of-total" },
          { label: "Page 1 of N", value: "page-n-of-total" },
        ],
      },
      { id: "start", label: "Start at", type: "number", default: 1, min: 0, max: 9999 },
      { id: "size", label: "Font size", type: "range", default: 11, min: 7, max: 28, step: 1, unit: "pt" },
    ],
    steps: steps(
      "Upload the PDF to paginate.",
      "Choose position, format and starting number.",
      "Download your numbered document."
    ),
    benefits: ["Six placement options", "Multiple numbering formats", "Custom start value"],
    faqs: commonFaqs,
  },

  /* ------------------------------------------------------------------ */
  /* EDIT                                                                */
  /* ------------------------------------------------------------------ */
  {
    slug: "edit-text",
    title: "Edit PDF",
    short: "Full annotation studio",
    description:
      "Open the full editor to add text, images, shapes, highlights, drawings and signatures anywhere on the page.",
    category: "edit",
    icon: Type,
    handler: "editor",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-violet-500 to-fuchsia-500",
    popular: true,
    keywords: ["editor", "annotate", "modify", "text"],
    steps: steps(
      "Upload a PDF to open it in the editor.",
      "Use the toolbar to add and arrange content.",
      "Export a flattened, ready-to-share PDF."
    ),
    benefits: ["Rich annotation toolkit", "Precise object controls", "Export back to PDF"],
    faqs: commonFaqs,
  },
  {
    slug: "add-text-box",
    title: "Add Text Box",
    short: "Type onto a page",
    description: "Drop styled text boxes anywhere on your PDF with full control over font, size and color.",
    category: "edit",
    icon: TextCursorInput,
    handler: "editor",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-indigo-500 to-blue-500",
    keywords: ["text", "type", "caption", "label"],
    faqs: commonFaqs,
  },
  {
    slug: "highlight",
    title: "Highlight Text",
    short: "Emphasize content",
    description: "Highlight important passages with translucent color markers, just like on paper.",
    category: "edit",
    icon: Highlighter,
    handler: "editor",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-yellow-500 to-amber-500",
    keywords: ["marker", "emphasize", "color"],
    faqs: commonFaqs,
  },
  {
    slug: "underline",
    title: "Underline Text",
    short: "Underline passages",
    description: "Add clean underlines beneath any text to draw attention to key details.",
    category: "edit",
    icon: Underline,
    handler: "editor",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-blue-500 to-sky-500",
    keywords: ["line", "emphasize"],
    faqs: commonFaqs,
  },
  {
    slug: "strike-through",
    title: "Strike Through",
    short: "Cross out text",
    description: "Strike through outdated or removed content while keeping it legible for review.",
    category: "edit",
    icon: Strikethrough,
    handler: "editor",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-rose-500 to-red-500",
    keywords: ["cross out", "delete text", "review"],
    faqs: commonFaqs,
  },
  {
    slug: "add-images",
    title: "Add Images",
    short: "Insert pictures",
    description: "Place logos, photos and stamps onto any page, then resize and position them precisely.",
    category: "edit",
    icon: ImagePlus,
    handler: "editor",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-fuchsia-500 to-pink-500",
    keywords: ["picture", "logo", "photo", "stamp"],
    faqs: commonFaqs,
  },
  {
    slug: "watermark",
    title: "Watermark PDF",
    short: "Brand every page",
    description: "Stamp a custom text watermark across every page with adjustable opacity, angle and color.",
    category: "edit",
    icon: Stamp,
    handler: "processor",
    processorId: "watermark",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-purple-500 to-violet-500",
    popular: true,
    outputSuffix: "watermarked",
    keywords: ["stamp", "brand", "draft", "confidential"],
    options: [
      { id: "text", label: "Watermark text", type: "text", default: "CONFIDENTIAL", placeholder: "e.g. DRAFT" },
      { id: "opacity", label: "Opacity", type: "range", default: 20, min: 5, max: 100, step: 5, unit: "%" },
      { id: "angle", label: "Angle", type: "range", default: 45, min: -90, max: 90, step: 5, unit: "°" },
      { id: "size", label: "Font size", type: "range", default: 60, min: 20, max: 160, step: 2, unit: "pt" },
      { id: "color", label: "Color", type: "color", default: "#7c3aed" },
    ],
    steps: steps(
      "Upload the PDF you want to watermark.",
      "Set your text, opacity, angle and color.",
      "Download every page with your watermark."
    ),
    benefits: ["Diagonal or straight", "Adjustable transparency", "Applied to all pages"],
    faqs: commonFaqs,
  },
  {
    slug: "whiteout",
    title: "Whiteout PDF",
    short: "Cover mistakes",
    description: "Paint opaque white (or colored) boxes over content you want to hide before sharing.",
    category: "edit",
    icon: Eraser,
    handler: "editor",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-slate-400 to-slate-600",
    keywords: ["cover", "hide", "erase", "correct"],
    faqs: commonFaqs,
  },
  {
    slug: "draw-shapes",
    title: "Draw Shapes",
    short: "Add lines & boxes",
    description: "Add rectangles, ellipses, lines and arrows with custom stroke and fill styles.",
    category: "edit",
    icon: Shapes,
    handler: "editor",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-emerald-500 to-green-500",
    keywords: ["rectangle", "circle", "arrow", "line"],
    faqs: commonFaqs,
  },
  {
    slug: "freehand",
    title: "Freehand Drawing",
    short: "Draw with a pen",
    description: "Sketch, circle and annotate freehand with a smooth pressure-friendly pen tool.",
    category: "edit",
    icon: Pencil,
    handler: "editor",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-orange-500 to-red-500",
    keywords: ["draw", "pen", "sketch", "ink"],
    faqs: commonFaqs,
  },
  {
    slug: "sticky-notes",
    title: "Sticky Notes",
    short: "Add comments",
    description: "Attach colorful sticky note comments to give feedback and mark up documents.",
    category: "edit",
    icon: StickyNote,
    handler: "editor",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-yellow-400 to-orange-400",
    keywords: ["comment", "note", "annotation", "feedback"],
    faqs: commonFaqs,
  },
  {
    slug: "link-inserter",
    title: "Link Inserter",
    short: "Add clickable links",
    description: "Turn any region of a page into a clickable hyperlink to a URL or another page.",
    category: "edit",
    icon: Link2,
    handler: "editor",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-sky-500 to-cyan-500",
    keywords: ["hyperlink", "url", "clickable"],
    faqs: commonFaqs,
  },

  /* ------------------------------------------------------------------ */
  /* FORMS                                                               */
  /* ------------------------------------------------------------------ */
  {
    slug: "fill-forms",
    title: "Fill PDF Forms",
    short: "Complete any form",
    description: "Detect and fill interactive form fields, or type anywhere on flat forms, then flatten to finish.",
    category: "forms",
    icon: FormInput,
    handler: "editor",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-sky-500 to-indigo-500",
    popular: true,
    keywords: ["form", "fill", "complete", "input"],
    faqs: commonFaqs,
  },
  {
    slug: "create-fillable-forms",
    title: "Create Fillable Forms",
    short: "Build form fields",
    description: "Add text fields, checkboxes and dropdowns to turn a static PDF into an interactive form.",
    category: "forms",
    icon: ListChecks,
    handler: "editor",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-indigo-500 to-violet-500",
    keywords: ["build form", "fields", "interactive"],
    faqs: commonFaqs,
  },
  {
    slug: "clear-form-fields",
    title: "Clear Form Fields",
    short: "Reset a form",
    description: "Instantly wipe all entered values from a form so it can be filled out fresh.",
    category: "forms",
    icon: FileX2,
    handler: "processor",
    processorId: "clearForm",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-rose-500 to-pink-500",
    outputSuffix: "cleared",
    keywords: ["reset", "empty form", "wipe"],
    steps: steps(
      "Upload a filled PDF form.",
      "We detect and reset every field.",
      "Download the blank, reusable form."
    ),
    benefits: ["Resets all field types", "Keeps the form interactive", "One-click reset"],
    faqs: commonFaqs,
  },
  {
    slug: "flatten",
    title: "Flatten PDF",
    short: "Lock in content",
    description: "Flatten form fields and annotations into the page so they can't be edited or changed.",
    category: "forms",
    icon: Layers,
    handler: "processor",
    processorId: "flatten",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-slate-500 to-gray-600",
    outputSuffix: "flattened",
    keywords: ["merge layers", "lock", "finalize"],
    steps: steps(
      "Upload a PDF with forms or annotations.",
      "We bake every field into the page.",
      "Download a final, non-editable PDF."
    ),
    benefits: ["Prevents further edits", "Universal compatibility", "Preserves appearance"],
    faqs: commonFaqs,
  },
  {
    slug: "e-signature",
    title: "Electronic Signature",
    short: "Sign documents",
    description: "Draw, type or upload your signature and place it precisely on any page, then download.",
    category: "forms",
    icon: PenTool,
    handler: "editor",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-violet-500 to-purple-500",
    popular: true,
    keywords: ["sign", "signature", "esign", "autograph"],
    faqs: commonFaqs,
  },
  {
    slug: "date-fields",
    title: "Date Fields",
    short: "Stamp dates",
    description: "Add formatted date stamps or interactive date fields anywhere on the document.",
    category: "forms",
    icon: Calendar,
    handler: "editor",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-cyan-500 to-blue-500",
    keywords: ["date", "timestamp", "calendar"],
    faqs: commonFaqs,
  },
  {
    slug: "checkbox-fields",
    title: "Checkbox Fields",
    short: "Add checkboxes",
    description: "Insert tickable checkbox fields for approvals, agreements and multiple choices.",
    category: "forms",
    icon: CheckSquare,
    handler: "editor",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-emerald-500 to-teal-500",
    keywords: ["checkbox", "tick", "check"],
    faqs: commonFaqs,
  },
  {
    slug: "radio-buttons",
    title: "Radio Buttons",
    short: "Single-choice fields",
    description: "Add grouped radio buttons so users can pick exactly one option per question.",
    category: "forms",
    icon: CircleDot,
    handler: "editor",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-fuchsia-500 to-purple-500",
    keywords: ["radio", "choice", "option"],
    faqs: commonFaqs,
  },
  {
    slug: "dropdown-fields",
    title: "Dropdown Fields",
    short: "Selectable lists",
    description: "Add dropdown selection fields to keep long forms compact and easy to complete.",
    category: "forms",
    icon: ChevronDownSquare,
    handler: "editor",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-indigo-500 to-sky-500",
    keywords: ["dropdown", "select", "combobox", "list"],
    faqs: commonFaqs,
  },

  /* ------------------------------------------------------------------ */
  /* SECURITY                                                            */
  /* ------------------------------------------------------------------ */
  {
    slug: "protect",
    title: "Protect PDF",
    short: "Add a password",
    description: "Encrypt your PDF with a password so only people you trust can open it.",
    category: "security",
    icon: Lock,
    handler: "processor",
    processorId: "protect",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-emerald-500 to-green-600",
    popular: true,
    outputSuffix: "protected",
    keywords: ["password", "encrypt", "lock", "secure"],
    options: [
      { id: "password", label: "Password", type: "password", default: "", placeholder: "Enter a strong password" },
    ],
    steps: steps(
      "Upload the PDF you want to secure.",
      "Set a password to open the document.",
      "Download the encrypted, password-protected PDF."
    ),
    benefits: ["Strong AES encryption", "Runs fully in your browser", "No password ever leaves your device"],
    faqs: [
      {
        question: "What encryption is used?",
        answer:
          "We apply industry-standard AES encryption directly in your browser. The password is used locally and is never transmitted anywhere.",
      },
      ...commonFaqs,
    ],
  },
  {
    slug: "unlock",
    title: "Unlock PDF",
    short: "Remove password",
    description: "Remove a known password from a PDF you own so it opens without prompting.",
    category: "security",
    icon: Unlock,
    handler: "processor",
    processorId: "unlock",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-amber-500 to-orange-500",
    outputSuffix: "unlocked",
    keywords: ["remove password", "decrypt", "open"],
    options: [
      { id: "password", label: "Current password", type: "password", default: "", placeholder: "The document's password" },
    ],
    steps: steps(
      "Upload the protected PDF.",
      "Enter the current password you already know.",
      "Download a copy with the password removed."
    ),
    benefits: ["Works on documents you own", "Fully offline", "Instant unlock"],
    faqs: [
      {
        question: "Can you unlock a PDF without the password?",
        answer:
          "No. For your privacy and to respect document ownership, you must provide the correct password. We only remove protection you can already bypass yourself.",
      },
      ...commonFaqs,
    ],
  },
  {
    slug: "redact",
    title: "Redact PDF",
    short: "Black out secrets",
    description: "Permanently cover sensitive text and images with opaque redaction boxes, then flatten.",
    category: "security",
    icon: SquareM,
    handler: "editor",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-slate-700 to-black",
    keywords: ["black out", "censor", "hide", "confidential"],
    faqs: commonFaqs,
  },
  {
    slug: "remove-metadata",
    title: "Remove Metadata",
    short: "Strip hidden data",
    description: "Erase author, title, keywords and other hidden metadata for a clean, anonymous PDF.",
    category: "security",
    icon: Tags,
    handler: "processor",
    processorId: "removeMetadata",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-teal-500 to-cyan-600",
    outputSuffix: "clean",
    keywords: ["strip", "anonymize", "privacy", "properties"],
    steps: steps(
      "Upload the PDF to sanitize.",
      "We strip all document metadata.",
      "Download a clean, anonymous file."
    ),
    benefits: ["Removes author & title", "Clears creation software", "Great before sharing"],
    faqs: commonFaqs,
  },
  {
    slug: "encrypt",
    title: "Encrypt PDF",
    short: "Owner + user locks",
    description: "Apply strong encryption with separate owner and user passwords for maximum control.",
    category: "security",
    icon: FileLock2,
    handler: "processor",
    processorId: "encrypt",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-green-600 to-emerald-700",
    outputSuffix: "encrypted",
    keywords: ["aes", "cipher", "secure", "lock"],
    options: [
      { id: "userPassword", label: "User password (to open)", type: "password", default: "", placeholder: "Required to open" },
      { id: "ownerPassword", label: "Owner password (to edit)", type: "password", default: "", placeholder: "Optional — controls permissions" },
    ],
    steps: steps(
      "Upload the PDF to encrypt.",
      "Set the user and optional owner passwords.",
      "Download the encrypted document."
    ),
    benefits: ["Separate open & edit rights", "AES encryption", "100% client-side"],
    faqs: commonFaqs,
  },
  {
    slug: "decrypt",
    title: "Decrypt PDF",
    short: "Strip encryption",
    description: "Provide the password to fully decrypt a document and save an unencrypted copy.",
    category: "security",
    icon: FileKey2,
    handler: "processor",
    processorId: "unlock",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-orange-500 to-amber-600",
    outputSuffix: "decrypted",
    keywords: ["remove encryption", "unlock", "open"],
    options: [
      { id: "password", label: "Password", type: "password", default: "", placeholder: "The document's password" },
    ],
    steps: steps(
      "Upload the encrypted PDF.",
      "Enter the correct password.",
      "Download the decrypted document."
    ),
    benefits: ["Removes all encryption", "Preserves content", "Runs offline"],
    faqs: commonFaqs,
  },
  {
    slug: "permission-settings",
    title: "Permission Settings",
    short: "Control what's allowed",
    description: "Restrict printing, copying and editing by locking permissions behind an owner password.",
    category: "security",
    icon: ShieldAlert,
    handler: "processor",
    processorId: "permissions",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-emerald-600 to-teal-700",
    outputSuffix: "restricted",
    keywords: ["permissions", "restrict", "printing", "copying"],
    options: [
      { id: "ownerPassword", label: "Owner password", type: "password", default: "", placeholder: "Required to change permissions" },
      { id: "allowPrinting", label: "Allow printing", type: "switch", default: true },
      { id: "allowCopying", label: "Allow copying text", type: "switch", default: false },
      { id: "allowModifying", label: "Allow editing", type: "switch", default: false },
    ],
    steps: steps(
      "Upload the PDF to restrict.",
      "Toggle which actions are allowed and set an owner password.",
      "Download the permission-controlled PDF."
    ),
    benefits: ["Block printing or copying", "Owner password enforced", "Granular control"],
    faqs: commonFaqs,
  },

  /* ------------------------------------------------------------------ */
  /* OCR                                                                 */
  /* ------------------------------------------------------------------ */
  {
    slug: "ocr",
    title: "OCR PDF",
    short: "Recognize scanned text",
    description: "Run optical character recognition over scanned pages to unlock the text they contain.",
    category: "ocr",
    icon: ScanText,
    handler: "processor",
    processorId: "ocr",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-amber-500 to-orange-500",
    popular: true,
    outputSuffix: "ocr",
    keywords: ["recognize", "scan", "text recognition", "tesseract"],
    options: [
      {
        id: "language",
        label: "Language",
        type: "select",
        default: "eng",
        options: [
          { label: "English", value: "eng" },
          { label: "Spanish", value: "spa" },
          { label: "French", value: "fra" },
          { label: "German", value: "deu" },
          { label: "Italian", value: "ita" },
          { label: "Portuguese", value: "por" },
        ],
      },
      {
        id: "output",
        label: "Output",
        type: "radio",
        default: "searchable",
        options: [
          { label: "Searchable PDF", value: "searchable", description: "Original pages + invisible text" },
          { label: "Plain text", value: "text", description: "Extracted .txt file" },
        ],
      },
    ],
    steps: steps(
      "Upload a scanned PDF.",
      "Choose the language and output format.",
      "Download a searchable PDF or extracted text."
    ),
    benefits: ["On-device recognition", "Searchable PDF output", "Multiple languages"],
    faqs: [
      {
        question: "Does OCR run on your servers?",
        answer:
          "No. Recognition runs entirely in your browser via WebAssembly. The language model is downloaded to your device on first use and cached for next time.",
      },
      ...commonFaqs,
    ],
  },
  {
    slug: "searchable-pdf",
    title: "Searchable PDF",
    short: "Make scans searchable",
    description: "Layer invisible, selectable text over scanned pages so your PDF becomes fully searchable.",
    category: "ocr",
    icon: FileSearch,
    handler: "processor",
    processorId: "ocr",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-orange-500 to-red-500",
    outputSuffix: "searchable",
    keywords: ["search", "index", "selectable"],
    options: [
      {
        id: "language",
        label: "Language",
        type: "select",
        default: "eng",
        options: [
          { label: "English", value: "eng" },
          { label: "Spanish", value: "spa" },
          { label: "French", value: "fra" },
          { label: "German", value: "deu" },
        ],
      },
      { id: "output", label: "Output", type: "text", default: "searchable" },
    ],
    steps: steps(
      "Upload a scanned or image-only PDF.",
      "Pick the document language.",
      "Download a searchable PDF you can select and copy from."
    ),
    benefits: ["Invisible text layer", "Keeps original look", "Copy & search enabled"],
    faqs: commonFaqs,
  },
  {
    slug: "extract-text",
    title: "Extract Text",
    short: "Pull out all text",
    description: "Extract the raw text content from any text-based PDF into a clean, plain-text file.",
    category: "ocr",
    icon: FileText,
    handler: "processor",
    processorId: "extractText",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-yellow-500 to-amber-600",
    outputSuffix: "text",
    keywords: ["copy text", "get text", "txt"],
    steps: steps(
      "Upload a text-based PDF.",
      "We read the embedded text layer.",
      "Download all the text as a .txt file."
    ),
    benefits: ["Preserves reading order", "Fast and lossless", "Great for reuse"],
    faqs: commonFaqs,
  },
  {
    slug: "extract-images",
    title: "Extract Images",
    short: "Save embedded images",
    description: "Pull every embedded image out of a PDF and download them together in a ZIP archive.",
    category: "ocr",
    icon: ImageDown,
    handler: "processor",
    processorId: "extractImages",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-amber-500 to-yellow-600",
    outputSuffix: "images",
    keywords: ["images", "pictures", "save photos"],
    steps: steps(
      "Upload a PDF containing images.",
      "We scan each page for embedded pictures.",
      "Download all images as a ZIP."
    ),
    benefits: ["Original resolution", "Bundled ZIP download", "Every page scanned"],
    faqs: commonFaqs,
  },
  {
    slug: "scan-to-editable",
    title: "Scan to Editable",
    short: "Digitize paper docs",
    description: "Convert a scanned document into recognized text you can copy, search and reuse.",
    category: "ocr",
    icon: FileType2,
    handler: "processor",
    processorId: "ocr",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-orange-600 to-amber-500",
    outputSuffix: "editable",
    keywords: ["digitize", "convert scan", "editable"],
    options: [
      {
        id: "language",
        label: "Language",
        type: "select",
        default: "eng",
        options: [
          { label: "English", value: "eng" },
          { label: "Spanish", value: "spa" },
          { label: "French", value: "fra" },
          { label: "German", value: "deu" },
        ],
      },
      { id: "output", label: "Output", type: "text", default: "text" },
    ],
    steps: steps(
      "Upload a scanned PDF.",
      "Choose the document language.",
      "Download the recognized, editable text."
    ),
    benefits: ["Turns scans into text", "On-device OCR", "Copy & edit anywhere"],
    faqs: commonFaqs,
  },

  /* ------------------------------------------------------------------ */
  /* CONVERT                                                             */
  /* ------------------------------------------------------------------ */
  {
    slug: "pdf-to-jpg",
    title: "PDF to JPG",
    short: "Pages to images",
    description: "Convert each PDF page into a high-quality JPG image, bundled together in a ZIP.",
    category: "convert",
    icon: FileImage,
    handler: "processor",
    processorId: "pdfToImages",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-rose-500 to-pink-500",
    popular: true,
    outputSuffix: "images",
    keywords: ["jpeg", "image", "picture", "export"],
    options: [
      {
        id: "quality",
        label: "Resolution",
        type: "select",
        default: "2",
        options: [
          { label: "Standard (1x)", value: "1" },
          { label: "High (2x)", value: "2" },
          { label: "Ultra (3x)", value: "3" },
        ],
      },
    ],
    steps: steps(
      "Upload your PDF.",
      "Choose the export resolution.",
      "Download every page as a JPG in a ZIP."
    ),
    benefits: ["Crisp high-DPI export", "One image per page", "ZIP bundle download"],
    faqs: commonFaqs,
  },
  {
    slug: "jpg-to-pdf",
    title: "JPG to PDF",
    short: "Images to PDF",
    description: "Turn one or many JPG images into a single, cleanly laid-out PDF document.",
    category: "convert",
    icon: Images,
    handler: "processor",
    processorId: "imagesToPdf",
    accept: ["image/jpeg", "image/jpg"],
    acceptLabel: "JPG images",
    multiple: true,
    maxFiles: 100,
    gradient: "from-pink-500 to-rose-500",
    popular: true,
    outputSuffix: "converted",
    keywords: ["jpeg", "photos", "combine images"],
    options: [
      {
        id: "pageSize",
        label: "Page size",
        type: "select",
        default: "fit",
        options: [
          { label: "Fit to image", value: "fit" },
          { label: "A4", value: "a4" },
          { label: "US Letter", value: "letter" },
        ],
      },
      {
        id: "orientation",
        label: "Orientation",
        type: "radio",
        default: "auto",
        options: [
          { label: "Auto", value: "auto" },
          { label: "Portrait", value: "portrait" },
          { label: "Landscape", value: "landscape" },
        ],
        showWhen: { id: "pageSize", equals: "a4" },
      },
      { id: "margin", label: "Margin", type: "range", default: 0, min: 0, max: 80, step: 4, unit: "pt" },
    ],
    steps: steps(
      "Upload one or more JPG images.",
      "Pick page size and margins.",
      "Download them combined into one PDF."
    ),
    benefits: ["Combine many images", "Choose page size", "Reorder before converting"],
    faqs: commonFaqs,
  },
  {
    slug: "png-to-pdf",
    title: "PNG to PDF",
    short: "PNGs to PDF",
    description: "Convert transparent or solid PNG images into a polished multi-page PDF.",
    category: "convert",
    icon: FileImage,
    handler: "processor",
    processorId: "imagesToPdf",
    accept: ["image/png"],
    acceptLabel: "PNG images",
    multiple: true,
    maxFiles: 100,
    gradient: "from-fuchsia-500 to-pink-500",
    outputSuffix: "converted",
    keywords: ["png", "images", "transparent"],
    options: [
      {
        id: "pageSize",
        label: "Page size",
        type: "select",
        default: "fit",
        options: [
          { label: "Fit to image", value: "fit" },
          { label: "A4", value: "a4" },
          { label: "US Letter", value: "letter" },
        ],
      },
      { id: "background", label: "Flatten transparency to white", type: "switch", default: true },
      { id: "margin", label: "Margin", type: "range", default: 0, min: 0, max: 80, step: 4, unit: "pt" },
    ],
    steps: steps(
      "Upload one or more PNG images.",
      "Choose page size and background handling.",
      "Download the combined PDF."
    ),
    benefits: ["Handles transparency", "Multi-image support", "Custom page sizing"],
    faqs: commonFaqs,
  },
  {
    slug: "pdf-to-txt",
    title: "PDF to TXT",
    short: "PDF to plain text",
    description: "Export all readable text from a PDF into a clean .txt file, ready for editing.",
    category: "convert",
    icon: FileText,
    handler: "processor",
    processorId: "extractText",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-rose-500 to-red-500",
    outputSuffix: "text",
    keywords: ["text", "txt", "plain"],
    steps: steps("Upload a text-based PDF.", "We extract the text layer.", "Download a .txt file."),
    benefits: ["Reading-order text", "Instant export", "Universal .txt format"],
    faqs: commonFaqs,
  },
  {
    slug: "pdf-to-word",
    title: "PDF to Word",
    short: "Editable .doc",
    description: "Convert a PDF's text into an editable Word document you can open in Microsoft Word.",
    category: "convert",
    icon: FileText,
    handler: "processor",
    processorId: "pdfToWord",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-blue-600 to-sky-500",
    popular: true,
    outputSuffix: "converted",
    keywords: ["docx", "doc", "microsoft word", "editable"],
    steps: steps(
      "Upload a text-based PDF.",
      "We rebuild it as a Word document.",
      "Download a .doc file ready to edit."
    ),
    benefits: ["Opens in Word & Google Docs", "Preserves text flow", "Fully client-side"],
    faqs: [
      {
        question: "Will the layout be identical?",
        answer:
          "This converter focuses on getting your text and paragraphs into an editable Word file. Complex multi-column layouts and scanned pages may need light cleanup after conversion.",
      },
      ...commonFaqs,
    ],
  },
  {
    slug: "word-to-pdf",
    title: "Word to PDF",
    short: ".docx to PDF",
    description: "Convert a Word document into a clean, universally viewable PDF in your browser.",
    category: "convert",
    icon: FileText,
    handler: "processor",
    processorId: "wordToPdf",
    accept: [
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      "application/msword",
    ],
    acceptLabel: "Word document (.docx)",
    gradient: "from-sky-500 to-blue-600",
    outputSuffix: "converted",
    keywords: ["docx", "doc", "microsoft word"],
    steps: steps(
      "Upload a .docx file.",
      "We render its content into a PDF.",
      "Download the finished PDF."
    ),
    benefits: ["Keeps paragraphs & headings", "No Office required", "Private & offline"],
    faqs: [
      {
        question: "Which Word files are supported?",
        answer:
          "Modern .docx files convert best. The converter reads the document's text and structure and renders it into a clean PDF entirely in your browser.",
      },
      ...commonFaqs,
    ],
  },
  {
    slug: "excel-to-pdf",
    title: "Excel to PDF",
    short: "Spreadsheets to PDF",
    description: "Turn Excel spreadsheets into tidy, printable PDF tables without leaving your browser.",
    category: "convert",
    icon: FileSpreadsheet,
    handler: "processor",
    processorId: "excelToPdf",
    accept: [
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "application/vnd.ms-excel",
    ],
    acceptLabel: "Excel file (.xlsx)",
    gradient: "from-emerald-500 to-green-600",
    outputSuffix: "converted",
    keywords: ["xlsx", "spreadsheet", "table"],
    steps: steps(
      "Upload an .xlsx spreadsheet.",
      "We lay each sheet out as a table.",
      "Download the resulting PDF."
    ),
    benefits: ["Renders sheet tables", "Multi-sheet support", "Clean gridlines"],
    faqs: commonFaqs,
  },
  {
    slug: "powerpoint-to-pdf",
    title: "PowerPoint to PDF",
    short: "Slides to PDF",
    description: "Convert PowerPoint slides into a shareable PDF, one page per slide.",
    category: "convert",
    icon: Presentation,
    handler: "processor",
    processorId: "pptToPdf",
    accept: [
      "application/vnd.openxmlformats-officedocument.presentationml.presentation",
      "application/vnd.ms-powerpoint",
    ],
    acceptLabel: "PowerPoint file (.pptx)",
    gradient: "from-orange-500 to-red-500",
    outputSuffix: "converted",
    keywords: ["pptx", "slides", "presentation"],
    steps: steps(
      "Upload a .pptx presentation.",
      "We place each slide's content on a page.",
      "Download the slide deck as a PDF."
    ),
    benefits: ["One page per slide", "Text & titles preserved", "No Office needed"],
    faqs: commonFaqs,
  },
  {
    slug: "pdf-to-html",
    title: "PDF to HTML",
    short: "PDF to web page",
    description: "Convert a PDF's text content into a clean, structured HTML document.",
    category: "convert",
    icon: FileCode2,
    handler: "processor",
    processorId: "pdfToHtml",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-indigo-500 to-blue-500",
    outputSuffix: "web",
    keywords: ["html", "web", "markup"],
    steps: steps(
      "Upload a text-based PDF.",
      "We convert each page into HTML sections.",
      "Download a ready-to-use .html file."
    ),
    benefits: ["Semantic page sections", "Editable markup", "Opens in any browser"],
    faqs: commonFaqs,
  },
  {
    slug: "html-to-pdf",
    title: "HTML to PDF",
    short: "Web page to PDF",
    description: "Convert an HTML file's content into a clean, paginated PDF document.",
    category: "convert",
    icon: Globe,
    handler: "processor",
    processorId: "htmlToPdf",
    accept: ["text/html"],
    acceptLabel: "HTML file",
    gradient: "from-blue-500 to-indigo-600",
    outputSuffix: "converted",
    keywords: ["html", "web page", "markup"],
    steps: steps(
      "Upload an .html file.",
      "We render its text content into pages.",
      "Download the generated PDF."
    ),
    benefits: ["Extracts readable content", "Auto pagination", "Runs offline"],
    faqs: commonFaqs,
  },

  /* ------------------------------------------------------------------ */
  /* UTILITIES                                                           */
  /* ------------------------------------------------------------------ */
  {
    slug: "view",
    title: "View PDF",
    short: "Read & navigate",
    description: "Open any PDF in a fast, distraction-free reader with zoom, search and page navigation.",
    category: "utilities",
    icon: Eye,
    handler: "viewer",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-cyan-500 to-blue-500",
    popular: true,
    keywords: ["read", "open", "reader", "preview"],
    faqs: commonFaqs,
  },
  {
    slug: "compare",
    title: "Compare PDFs",
    short: "Spot the differences",
    description: "Place two PDFs side by side and highlight textual differences between them.",
    category: "utilities",
    icon: GitCompareArrows,
    handler: "viewer",
    processorId: "compare",
    accept: PDF_ACCEPT,
    acceptLabel: "Two PDF files",
    multiple: true,
    minFiles: 2,
    maxFiles: 2,
    gradient: "from-blue-500 to-indigo-500",
    keywords: ["diff", "difference", "versions"],
    faqs: commonFaqs,
  },
  {
    slug: "document-information",
    title: "Document Information",
    short: "Inspect properties",
    description: "Reveal a PDF's metadata, page count, sizes, version and security settings at a glance.",
    category: "utilities",
    icon: Info,
    handler: "processor",
    processorId: "docInfo",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-sky-500 to-cyan-500",
    keywords: ["metadata", "properties", "details", "info"],
    steps: steps(
      "Upload any PDF.",
      "We inspect its internal structure.",
      "Review a detailed properties report."
    ),
    benefits: ["Full metadata readout", "Page & size details", "Encryption status"],
    faqs: commonFaqs,
  },
  {
    slug: "page-size-detection",
    title: "Page Size Detection",
    short: "Measure every page",
    description: "Detect the exact dimensions and named format (A4, Letter…) of each page in your PDF.",
    category: "utilities",
    icon: Ruler,
    handler: "processor",
    processorId: "pageSizes",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-cyan-500 to-teal-500",
    keywords: ["dimensions", "a4", "letter", "measure"],
    steps: steps(
      "Upload your PDF.",
      "We measure each page.",
      "See a per-page size and format breakdown."
    ),
    benefits: ["Millimeter & point sizes", "Named format detection", "Per-page report"],
    faqs: commonFaqs,
  },
  {
    slug: "thumbnail-generator",
    title: "Thumbnail Generator",
    short: "Create page previews",
    description: "Generate crisp PNG thumbnails for every page and download them as a ZIP.",
    category: "utilities",
    icon: LayoutGrid,
    handler: "processor",
    processorId: "thumbnails",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-blue-500 to-cyan-500",
    outputSuffix: "thumbnails",
    keywords: ["preview", "thumbnails", "grid"],
    options: [
      {
        id: "width",
        label: "Thumbnail width",
        type: "select",
        default: "320",
        options: [
          { label: "Small (200px)", value: "200" },
          { label: "Medium (320px)", value: "320" },
          { label: "Large (480px)", value: "480" },
        ],
      },
    ],
    steps: steps(
      "Upload your PDF.",
      "Choose a thumbnail size.",
      "Download a ZIP of page previews."
    ),
    benefits: ["Every page rendered", "Custom sizing", "ZIP bundle"],
    faqs: commonFaqs,
  },
  {
    slug: "duplicate-page",
    title: "Duplicate Page",
    short: "Clone pages",
    description: "Duplicate any page and insert the copy exactly where you need it in the document.",
    category: "utilities",
    icon: CopyPlus,
    handler: "processor",
    processorId: "duplicatePage",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF file",
    gradient: "from-indigo-500 to-blue-500",
    outputSuffix: "duplicated",
    keywords: ["copy", "clone", "repeat page"],
    options: [
      { id: "page", label: "Page to duplicate", type: "number", default: 1, min: 1, max: 9999 },
      { id: "times", label: "Copies", type: "number", default: 1, min: 1, max: 50 },
    ],
    steps: steps(
      "Upload your PDF.",
      "Choose which page to clone and how many times.",
      "Download the expanded document."
    ),
    benefits: ["Clone any page", "Multiple copies", "Inserted in place"],
    faqs: commonFaqs,
  },
  {
    slug: "replace-page",
    title: "Replace Page",
    short: "Swap a page",
    description: "Replace a page in your PDF with a page from another PDF, keeping everything else intact.",
    category: "utilities",
    icon: Replace,
    handler: "processor",
    processorId: "replacePage",
    accept: PDF_ACCEPT,
    acceptLabel: "Two PDF files",
    multiple: true,
    minFiles: 2,
    maxFiles: 2,
    gradient: "from-violet-500 to-indigo-500",
    outputSuffix: "replaced",
    keywords: ["swap", "substitute", "change page"],
    options: [
      { id: "target", label: "Page to replace (in first PDF)", type: "number", default: 1, min: 1, max: 9999 },
      { id: "source", label: "Replacement page (in second PDF)", type: "number", default: 1, min: 1, max: 9999 },
    ],
    steps: steps(
      "Upload the base PDF, then the PDF with the replacement page.",
      "Pick which page to replace and which page to use.",
      "Download the updated document."
    ),
    benefits: ["Precise page swap", "Two-document workflow", "Everything else preserved"],
    faqs: commonFaqs,
  },
];

/* ------------------------------------------------------------------ */
/* Derived lookups                                                     */
/* ------------------------------------------------------------------ */

export const TOOL_MAP: Record<string, Tool> = Object.fromEntries(
  TOOLS.map((t) => [t.slug, t])
);

export function getTool(slug: string): Tool | undefined {
  return TOOL_MAP[slug];
}

export function toolsByCategory(categoryId: string): Tool[] {
  return TOOLS.filter((t) => t.category === categoryId);
}

export const POPULAR_TOOLS: Tool[] = TOOLS.filter((t) => t.popular);

export const TOOL_COUNT = TOOLS.length;
